server:
  port: 9898
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.130:9300
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  rabbitmq:
    host: 192.168.56.130
    virtual-host: /leyou
    username: leyou
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
